
title: CSCI-UA 201 (Computer Systems Organization)
short_title: CS 201
description: "Course website for CSCI-UA 201 (Computer Systems Organization) course."

baseurl: "/cs201_s20" # the subpath of your site, e.g. /blog
url: "https://joannakl.github.io/cs201_s20" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown
kramdown:
  entity_output: numeric
  smart_quotes: apos,apos,quot,quot

exclude:
  - Gemfile
  - Gemfile.lock



course_number: "CSCI-UA 201"
course_name: "Computer Systems Organization"
course_section: "003"
course_semester: "Spring 2020"
course_time: "<br>Tuesdays and Thursdays 9:30AM - 10:45AM, CIWW, Room 109"

recitation_section1: "004"
recitation_time1:  "Mondays 11:00AM - 12:15PM, CIWW 202"
recitation_section2: "007"
recitation_time2:  "Mondays 3:30PM - 4:45PM, CIWW 202"
recitation_section3: "008"
recitation_time3:  "Wednesdays 3:30PM - 4:45PM, CIWW 202"
recitation_instructor1_full: "Justin Mae "
recitation_instructor2_full: "Goktug Saatcioglu"
recitation_instructor1_name: "Justin"
recitation_instructor2_name: "Goktug"
course_assistant_name: "Muge"
course_assistant_name_full: "Muge Chen"


instructor_office_hours: "Mondays 12:30 - 2:30pm, Thursdays 11:00am - 12:00pm,
(or you can schedule an appointment if these times do not work for you)"
instructor_office_hours_location: "423 CIWW"
recitation1_office_hours: "Tuesdays 11:00-12:30, Wednesdays 10:00-11:30"
recitation1_office_hours_location: "412 CIWW"
recitation2_office_hours: "Mondays 1:00-2:30 "
recitation2_office_hours_location: "412 CIWW"
course_assistant_office_hours: "Wednesdays 1:00-3:00pm, Fridays 1:00-3:00pm"
course_assistant_office_hours_location: "412 CIWW"

current_course1_title: "CSCI 201 sec. 3"
current_course1_link: "https://cs.nyu.edu/~joannakl/cs201_s20/"
current_course2_title: "CSCI 480 sec. 4 (APS)"
current_course2_link: "https://cs.nyu.edu/~joannakl/aps_s20/"
current_course3_title: "CSCI 480 sec. 10 (OSSD)"
current_course3_link: "https://cs.nyu.edu/~joannakl/ossd_s20/"

#tutor_location: "406 WWH"
#tutor_schedule_link: "http://cims.nyu.edu/~joannakl/CSCI102_common/#tutoring"

online_test_date: "Feb. 20, during class time"
midterm_exam_date: "March 10, during class time"
final_exam_date: "May 18 (Monday), 8:00-9:50am"
final_exams_link: "http://cs.nyu.edu/dynamic/courses/exams/"

piazza_site: http://piazza.com/nyu/spring2020/csci201
gradescope_site: "https://gradescope.com/"
github_site: "https://github.com/nyu-cs201-s20"

book_required: "Computer Systems: A Programmer's Perspective, "
book_required_author: "Randal E. Bryant and David R. O'Hallaron, "
book_required_edition: "**3rd** edition, "
book_required_link: http://csapp.cs.cmu.edu/
book_required_note: " (the previous editions of the book will not work, international edition of the book
had some mistakes as of a year ago) "
book_required_image: "http://csapp.cs.cmu.edu/3e/images/csapp3e-cover.jpg"

book_opt_1: "The C programming language, "
book_opt_1_author: "Brian W. Kernighan, Dennis Ritchie, "
book_opt_1_edition: "**2nd** edition, "
book_opt_1_link: ""
book_opt_1_note: "Optional, but strongly recommended (you can use any C programming book as an alternative)."
book_opt_1_image: "https://www.pearsonhighered.com/assets/bigcovers/0/1/3/3/0133086216.jpg"


book_opt_2: "C Essential Training, "
book_opt_2_author: "Isac Artzi, "
book_opt_2_edition: "Lynda.com tutorial, "
book_opt_2_link: "https://www.lynda.com/C-tutorials/C-Essential-Training/164457-2.html?org=nyu.edu"
book_opt_2_note: "You can use this online tutorial to dig into topics that you do not feel confident on.
But you should be compiling your code using GCC, not Eclipse."
book_opt_2_image: "https://cdn.lynda.com/static/images/consumermigration/Lynda Icon_2x.png"


book_opt_3: "Dive Into Systems, "
book_opt_3_author: "Suzanne J. Mathews, Tia Newhall, Kevin C. Webb, "
book_opt_3_edition: "online book "
book_opt_3_link: "https://diveintosystems.cs.swarthmore.edu/x86_64/antora/diveintosystems/beta/index.html"
book_opt_3_note: "(make sure that you access the x86_64 editiion) "
book_opt_3_image: ""
